# -*- coding: utf-8 -*-
"""Expense_Tracker

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NH1DqZFzZYwxXoTMPiwiom0ydfQgJvbS
"""

import matplotlib.pyplot as plt
import sqlite3

def create_db():
  conn=sqlite3.connect('expenses.db')
  cursor = conn.cursor()
  cursor.execute('''CREATE TABLE IF NOT EXISTS expenses (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      name TEXT,
      amount REAL,
      category TEXT,
      date TEXT)''')
  conn.commit()
  conn.close()

def load_expenses():
  conn=sqlite3.connect('expenses.db')
  cursor=conn.cursor()
  cursor.execute('SELECT id, name, amount,category, date FROM expenses')
  rows = cursor.fetchall()
  conn.close()
  return rows

def add_expense():
  print('Add to expenses to selected')
  print('Categories')
  print("________________")
  print('1.Food')
  print('2.Automotive')
  print('3.Utilities')
  print('4.Entertainment')
  print('5.Shopping')
  print('6.Other')
  print('0.Reurn to Main Menu')
  category= input('Enter the category number')
  if category == '0':
    return
  if category == '1':
    category='Food'
  elif category == '2':
    category = 'Automotive'
  elif category == '3':
    category = 'Utilities'
  elif category == '4':
    category = 'Entertainment'
  elif category == '5':
    category = 'Shopping'
  elif category == '6':
    other=input('Enter the name of Category')
    category = other



  expense_name=input('Enter the name of the Expense')
  date=input('Enter the date (MM/DD/YYYY): ')
  try:
    amount=float(input('Enter the amount of the expense'))
  except ValueError:
    print('Invalid value input, try again')
    return
  conn=sqlite3.connect('expenses.db')
  cursor=conn.cursor()
  cursor.execute('INSERT INTO expenses (name, amount, category, date) VALUES(?,?,?,?)',
                 (expense_name, amount, category, date))
  conn.commit()
  conn.close()
  print(f'{category}: {expense_name}: ${amount:.2f} added')

def view_expenses():
  print('View Expenses')
  print('______________')
  expenses=load_expenses()
  if len(expenses)==0:
    print('There are no expenses added yet')
    return
  print(f"Total amount of expense {len(expenses)}")
  for expense in expenses:
      print(f"{expense[0]} | {expense[3]} | {expense[1]} | ${expense[2]:.2f} | {expense[4]}")

def delete_expense():
  print('Delete Expense')
  print('______________')
  expenses=load_expenses()
  if len(expenses)==0:
    print('There are no expenses added yet')
    return
  view_expenses()
  try:
    delete=int(input('Select the expense to delete'))
  except ValueError:
    print('Invalid input entered. Please try again')
    return
  ids=[expense[0] for expense in expenses]
  if delete not in ids:
    print('Sorry, invalid ID entered. Please try again')
    return

  conn=sqlite3.connect('expenses.db')
  cursor=conn.cursor()
  cursor.execute('DELETE FROM expenses WHERE id = ?', (delete,))
  conn.commit()
  conn.close()
  print('Expense deleted')

def view_summary():
  print('View Expenses')
  print('______________')
  expenses=load_expenses()
  if len(expenses)==0:
    print('There are no expenses added yet')
    return
  categories=[expense[3] for expense in expenses]
  amounts=[expense [2] for expense in expenses]
  dates=[expense [4] for expense in expenses]
  total=0
  for expense in expenses:
    print(f"{expense[3]} | {expense[1]} | ${expense[2]:.2f} | {expense[4]}")
    total+= expense[2]
  print(f'Total amount of expenses: ${total:.2f}')

  category_totals={}
  for expense in expenses:
    cat=expense[3]
    category_totals[cat]=category_totals.get(cat,0)+ expense[2]

  top_category=max(category_totals, key=category_totals.get)
  print(f'Highest spending category is: {top_category}-${category_totals[top_category]:.2f}')


  print
  plt.bar(categories,amounts)
  plt.xlabel('Category')
  plt.ylabel("Amount")
  plt.title('Expense Summary')
  plt.show()

  plt.pie(amounts, labels=categories, autopct='%1.1f%%')
  plt.title('Expense Summary')
  plt.show()


  plt.plot(dates, amounts, marker='o')
  plt.xlabel('Date')
  plt.ylabel('Amount ($)')
  plt.title('Spending overtime')
  plt.xticks(rotation=45)
  plt.tight_layout()
  plt.show()

def filter_expenses():
  print('Search and Filter')
  print('_________________')
  expenses= load_expenses()
  if len(expenses)==0:
    print('There are no expenses added yet')
    return
  print('1. Fliter by Category')
  print('2. Filter by Date')
  print('0. return to Main Menu')

  choice= input('Select an option')
  if choice == '1':
    category=input('Enter the category')
    conn=sqlite3.connect('expenses.db')
    cursor=conn.cursor()
    cursor.execute('SELECT id, name, amount, category, date FROM expenses WHERE category LIKE ?', ('%' + category +  '%',))
    results=cursor.fetchall()
    conn.close()

  elif choice == '2':
    date=input('Enter the date (MM/DD/YYYY)')
    conn=sqlite3.connect('expenses.db')
    cursor=conn.cursor()
    cursor.execute ('SELECT id, name, amount, category, date FROM expenses WHERE date =?',(date,))
    results=cursor.fetchall()
    conn.close()

  elif choice == '0':
    return

  if len(results) == 0:
    print('No results found')
    return

  for expense in results:
    print(f"{expense[0]}. {expense[4]} | {expense [3]} | {expense[1]} | ${expense[2]:.2f}")

create_db()

while True:
  print('**Main Menu**')
  print('______________)')
  print('Select an Option')
  print('1. Add Expense')
  print('2. View Expenses')
  print('3. Delete Expense')
  print('4. View Summary')
  print('5. Search and Filter')
  print('6. Exit')

  option=input('Select the number of the option from the menu')
  if option == '1':
    add_expense()
  elif option == '2':
    view_expenses()
  elif option == '3':
    delete_expense()
  elif option  == '4':
    view_summary()
  elif option == '5':
    filter_expenses()
  elif option =='6' :
    break

  else:
    print('Invalid number entered, please try again')

